# -*- coding: utf-8 -*-
"""VIT/KNN

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hNpY4WWT9q6n7Ir9OmkREx81qDLcKjtf
"""

!pip install -q datasets transformers scikit-learn pillow torch torchvision matplotlib

from datasets import load_dataset
from transformers import ViTImageProcessor, ViTModel
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import (
    accuracy_score,
    f1_score,
    precision_score,
    recall_score,
    average_precision_score,
    precision_recall_curve,
    classification_report,
    confusion_matrix,
    ConfusionMatrixDisplay
)
from PIL import Image
from collections import Counter
import numpy as np
import torch
import matplotlib.pyplot as plt


dataset = load_dataset("Hemg/AI-Generated-vs-Real-Images-Datasets")
full = dataset["train"]

print("Dataset loaded.")
print(full)


sample_size = 3000
if len(full) > sample_size:
    full = full.shuffle(seed=42).select(range(sample_size))

print("Dataset size being used:", len(full))


print("Class balance:", Counter(full["label"]))

if hasattr(full.features["label"], "names"):
    label_names = full.features["label"].names
    print("Label names:", label_names)
else:
    label_names = ["AI", "Real"]

class_names = ["AI", "Real"]


np.random.seed(42)
n = len(full)
n_train = int(0.70 * n)
n_val = int(0.15 * n)
n_test = n - n_train - n_val

indices = np.random.permutation(n)
train_hf = full.select(indices[:n_train])
val_hf = full.select(indices[n_train:n_train + n_val])
test_hf = full.select(indices[n_train + n_val:])

print(f"Split — Train: {len(train_hf)} | Val: {len(val_hf)} | Test: {len(test_hf)}")

# -------------------------
# ViT processor/model
# -------------------------
processor = ViTImageProcessor.from_pretrained("google/vit-base-patch16-224-in21k")
vit_model = ViTModel.from_pretrained("google/vit-base-patch16-224-in21k")

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
vit_model.to(device)
vit_model.eval()

print("Using device:", device)

def get_embedding(image):
    if not isinstance(image, Image.Image):
        image = Image.fromarray(image)
    image = image.convert("RGB")

    inputs = processor(images=image, return_tensors="pt")
    inputs = {k: v.to(device) for k, v in inputs.items()}

    with torch.no_grad():
        outputs = vit_model(**inputs)


    return outputs.last_hidden_state[:, 0, :].squeeze().cpu().numpy()

def build_embeddings(hf_dataset):
    X, y = [], []
    for ex in hf_dataset:
        X.append(get_embedding(ex["image"]))
        y.append(ex["label"])
    return np.array(X), np.array(y)

print("Creating train embeddings...")
X_train, y_train = build_embeddings(train_hf)

print("Creating validation embeddings...")
X_val, y_val = build_embeddings(val_hf)

print("Creating test embeddings...")
X_test, y_test = build_embeddings(test_hf)

print("Train shape:", X_train.shape)
print("Validation shape:", X_val.shape)
print("Test shape:", X_test.shape)

k_values = [1, 3, 5, 7, 9]
best_k = None
best_f1 = -1
best_model = None

for k in k_values:
    knn = KNeighborsClassifier(n_neighbors=k)
    knn.fit(X_train, y_train)
    val_pred = knn.predict(X_val)
    val_f1 = f1_score(y_val, val_pred, average="weighted")
    print(f"k={k} | Validation F1={val_f1:.4f}")

    if val_f1 > best_f1:
        best_f1 = val_f1
        best_k = k
        best_model = knn

print(f"\nBest k based on validation F1: {best_k}")


val_pred = best_model.predict(X_val)
val_proba = best_model.predict_proba(X_val)[:, 1] if len(np.unique(y_val)) == 2 else None

print("\n===== Validation Results =====")
print(f"Accuracy:  {accuracy_score(y_val, val_pred):.4f}")
print(f"F1-score:  {f1_score(y_val, val_pred, average='weighted'):.4f}")
print(f"Precision: {precision_score(y_val, val_pred, average='weighted'):.4f}")
print(f"Recall:    {recall_score(y_val, val_pred, average='weighted'):.4f}")

if val_proba is not None:
    print(f"PR-AUC:    {average_precision_score(y_val, val_proba):.4f}")


test_pred = best_model.predict(X_test)
test_proba = best_model.predict_proba(X_test)[:, 1] if len(np.unique(y_test)) == 2 else None

print("\n===== Test Results =====")
print(f"Accuracy:  {accuracy_score(y_test, test_pred):.4f}")
print(f"F1-score:  {f1_score(y_test, test_pred, average='weighted'):.4f}")
print(f"Precision: {precision_score(y_test, test_pred, average='weighted'):.4f}")
print(f"Recall:    {recall_score(y_test, test_pred, average='weighted'):.4f}")

if test_proba is not None:
    print(f"PR-AUC:    {average_precision_score(y_test, test_proba):.4f}")

print("\nClassification Report:")
print(classification_report(y_test, test_pred))


if test_proba is not None:
    precision_vals, recall_vals, _ = precision_recall_curve(y_test, test_proba)
    plt.figure(figsize=(6, 4))
    plt.plot(recall_vals, precision_vals)
    plt.xlabel("Recall")
    plt.ylabel("Precision")
    plt.title("Precision-Recall Curve: ViT + KNN")
    plt.grid(True)
    plt.show()


cm_val = confusion_matrix(y_val, val_pred)
disp_val = ConfusionMatrixDisplay(confusion_matrix=cm_val, display_labels=class_names)
plt.figure(figsize=(6, 6))
disp_val.plot(cmap="Blues", xticks_rotation=90)
plt.title("Confusion Matrix for Validation")
plt.show()


cm_test = confusion_matrix(y_test, test_pred)
disp_test = ConfusionMatrixDisplay(confusion_matrix=cm_test, display_labels=class_names)
plt.figure(figsize=(6, 6))
disp_test.plot(cmap="Blues", xticks_rotation=90)
plt.title("Confusion Matrix for Test")
plt.show()